name: Extract WordPress Hooks

on:
  push:
    branches: [main, master]
    paths: ["**.php"]
  workflow_dispatch:

jobs:
  extract-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akirk/extract-wp-hooks@main
